### ISSUE TITLE
use function to create the precip, elev, and geology maps

### ISSUE THREAD

**Issue by kbrannan** [Creutzx/WatershedMap#3]
Next, use the function you created in the ElevMap repo in the loop you used in this repo to generate the mxd files

**Comment by Creutzx** [comment]
I think some of the 7 arguments in the first line of code may not be necessary, but I think that would depend on how the function is used.

**Comment by Creutzx** [comment]
After thinking about it some more, I think you were probably getting at a script that uses the simpler code for creating a single map (ElevMap), but switching out the arguments so that the different maps are created.

**Comment by kbrannan** [comment]
Roger that

**Comment by Creutzx** [comment]
I created a new repository for this:

https://github.com/Creutzx/WaterFunc/invitations

and added you as a collaborator.

The issue I'm having is passing a string as the argument into the function. e.g., how to get waterfunc(lyr_name=Geo) to work. The argument (lyr_name) in the def statement is greyed out--not sure what is going on there. Right now I'm looking into the *args approach.

**Comment by Creutzx** [comment]
I figured it out, it's ready.

**Comment by kbrannan** [comment]
Great!
Take a look at the file I created to use the function in a script. The file is in the kevcheck branch
WatershedMap/use_function.py

See if the function works in the script.

**Comment by Creutzx** [comment]
I have a question about creating this function with the list of many arguments, like here:
https://github.com/Creutzx/WatershedMap/blob/e828f2ac77cbc86cda96f5ae06ebf883f937922b/use_function.py#L13
I'm assuming this buys us some flexibility when applying this to a different watershed, although  the function assigns the variable names to specific paths in the directory, like here:
https://github.com/Creutzx/WatershedMap/blob/e828f2ac77cbc86cda96f5ae06ebf883f937922b/use_function.py#L5
There's a version I made in the [WaterFunc](https://github.com/Creutzx/WaterFunc/invitations) repository wherein the function takes a single argument to generate the maps, like here:
https://github.com/Creutzx/WaterFunc/blob/a0e0c0042124732d66905a1e7aa443fc6446da02/WaterFunc.py#L35
It would probably take a better understanding (on my part) of how this function will fit into the bigger picture, but I'd like to figure out what cases each approach would be best suited to.

**Comment by kbrannan** [comment]
Hi Brian,

Nice work!  Take the script from https://github.com/Creutzx/WatershedMap/blob/e828f2ac77cbc86cda96f5ae06ebf883f937922b/use_function.py#L13 and put the input for the function (line 3-11) in a text file. Now in the script, read the text file to populate the input variables for the function, then execute the function.

With respect to the work you’re doing, I need people to help automate these processes more than I need help to manually generate content. Your work serves multiple purposes, such as developing people with the skill-base to develop more tools for analysis in TMDLs, provide methods that are both transparent and reproducible, and have procedures that are easily archived. Brute forcing the generation of content through manual analysis doesn’t satisfactory meet these needs I listed no matter how good the documentation.

You’re doing really well and I hope you can stick with it. There are some more complex task on the near horizon and I want to make sure you have the skills to tackle them.

Thanks,
Kevin

**Comment by Creutzx** [comment]
Sounds good, I'm 100% behind the automation efforts, and really like doing this.

I updated the master branch along the lines of what I think you were asking for.  I did see numerous people warning against executing code from a .txt file, but I'm assuming that isn't relevant to this case.

My main question on this part right now is what arguments should be passed to the WatershedMap function--I think there's something I'm missing there.

**Comment by Creutzx** [comment]
I'm still getting an error when trying to call up the text file. I'll keep working on it, but here's what I'm using to read it:

https://github.com/Creutzx/WatershedMap/blob/7308ac94311da012b7950d55187b6babb2246660/WatershedMap.py#L5

**Comment by Creutzx** [comment]
my most recent commit on the master branch works now, let me know if you agree.

**Comment by kbrannan** [comment]
this issue has migrated to read input files issue
