### ISSUE TITLE
read input values

### ISSUE THREAD

**Issue by kbrannan** [Creutzx/WatershedMap#4]
take a look at the following script to ssee how you can read the input values from a file
WatershedMap/try_func.py

Compare the code on the script to the way you did the function to see how to call the function

I didn't work on assigning the values from the file to the variables in the function. I'll leave that to you

**Comment by Creutzx** [comment]
I have a few questions:

I thought that the arguments were just listed to be later defined and called by the function. Is one of the enhancements here that arguments are listed and defined in the text file?

https://github.com/Creutzx/WatershedMap/blob/a6462f16d9e787e4adbee46af8d026aca8bce471/try_func.py#L3

Another question about this line: is this necessary, or is there a better way for python to incorporate the code from the text file.

https://github.com/Creutzx/WatershedMap/blob/a6462f16d9e787e4adbee46af8d026aca8bce471/try_func.py#L12

Also, when running the function (the last line of the code), I'm getting an error, but I think it's related to problems with assigning the variables.

https://github.com/Creutzx/WatershedMap/blob/a6462f16d9e787e4adbee46af8d026aca8bce471/try_func.py#L28

Overall, I see what you're getting at with this re-structuring--when you mentioned assigning values from the file, you meant a different file from the _kmb.txt file you created, right? Or am I coding a way to read and extract only the variable names, etc from a single file?

**Comment by kbrannan** [comment]
check oout what I did to assign the vaules from the text file to the variables in the function
https://github.com/Creutzx/WatershedMap/blob/0a9d2dd5fec33a3fcf49521e91774f32a0533b55/try_func.py#L10-L15

**Comment by Creutzx** [comment]
Thanks! What's next?

**Comment by kbrannan** [comment]
Incorperate the changes into the function and remove the "try_func.py" from the repo and pull to master.
Next will cleaning up our work and have final version of files. Then we will include Bernedette in our work. You can bring her up to speed on your work.

**Comment by Creutzx** [comment]
Done and thanks! Let me know if there's anything else to do before our meeting.
